# SixthSense Artifact

Artifact of the paper "SixthSense: Debugging Convergence Problems in Probabilistic
Programs via Program Representation Learning" from FASE'2022.

To access ChameleonCloud resources, you may need the account to log in to ChameleonCloud. You also need to have a project to allocate resources (e.g., node).

In [1]:
from chi import context

context.version = "1.0"

context.choose_site(default="CHI@TACC")
context.choose_project()

### Check available hardware

In [2]:
from chi import hardware

node_type = "compute_cascadelake_r"
available_nodes = hardware.get_nodes(node_type=node_type, filter_reserved=True)
if available_nodes:
    print(f"There currently are {len(available_nodes)} {node_type} nodes ready to use")
else:
    print(f"All {node_type} nodes are in use! You could use next_free_timeslot to see how long you need to wait, or use the calendar.")

There currently are 28 compute_cascadelake_r nodes ready to use


### Reserve node

In [3]:
from chi import lease
from datetime import timedelta
import os

my_lease = lease.Lease(f"{os.getenv('USER')}-power-management", duration=timedelta(hours=3))
my_lease.add_node_reservation(nodes=[available_nodes[0]]) # or you could use node_type=node_type
my_lease.add_fip_reservation(1) # include a floating ip
my_lease.submit(idempotent=True)

Waiting for lease to start... This can take up to 60 seconds


Lease radhofanazizi_gmail_com-power-management has reached status active


### Create a server on the node

In [4]:
from chi import server

my_server = server.Server(
    f"{os.getenv('USER')}-power-management",
    reservation_id=my_lease.node_reservations[0]["id"],
    image_name="CC-Ubuntu22.04", # or use image_name
)
my_server.submit(idempotent=True)

Waiting for server radhofanazizi_gmail_com-power-management's status to become ACTIVE. This typically takes 10 minutes, but can take up to 20 minutes.


Server has moved to status ACTIVE


### Configure networking on the node

In [5]:
fip = my_lease.get_reserved_floating_ips()[0]
my_server.associate_floating_ip(fip)
my_server.check_connectivity(host=fip)

Checking connectivity to 129.114.109.72 port 22.


Connection successful


## Run SixthSense

Now, we can finally run SixthSense. First we need to clone the github repo first and then run the reproduce.sh script which contain the instructions from README.md
packaged into a bash file

In [24]:
my_server.execute("rm -rf sixthsense")

<Result cmd='rm -rf sixthsense' exited=0>

In [25]:
my_server.execute("git clone https://github.com/radhofan/sixthsense.git")

Cloning into 'sixthsense'...


<Result cmd='git clone https://github.com/radhofan/sixthsense.git' exited=0>

In [26]:
my_server.execute("chmod +x sixthsense/reproduce.sh")
my_server.execute("bash sixthsense/reproduce.sh")

ERROR: File or directory already exists: '/home/cc/miniconda'
If you want to update an existing installation, use the -u option.


Channels:
 - conda-forge
 - defaults
Platform: linux-64
Solving environment: ...working... done

# All requested packages already installed.

Running `shell init`, which:
 - modifies RC file: "/home/cc/.bashrc"
 - generates config for root prefix: "/home/cc/miniconda"
 - sets mamba executable to: "/home/cc/miniconda/bin/mamba"
The following has been added in your "/home/cc/.bashrc" file

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba shell init' !!
export MAMBA_EXE='/home/cc/miniconda/bin/mamba';
export MAMBA_ROOT_PREFIX='/home/cc/miniconda';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias mamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<



warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
    
warning  libmamba Please make sure you understand Anaconda Terms of Services.
    
warning  libmamba See: https://legal.anaconda.com/policies/en/
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
    
warning  libmamba Please make sure you understand Anaconda Terms of Services.
    
warning  libmamba See: https://legal.anaconda.com/policies/en/
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
    
warning  libmamba Please make sure you understand Anaconda Terms of Services.
    
warning  libmamba See: https://legal.anaconda.com/policies/en/
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
    
warning  libmamba Please make sure you understand Anaconda Terms of Services.
    
warning  libmamba See: https://legal.anaconda.com/policies/en/
DEPRECATION: --no-python



Transaction

  Prefix: /home/cc/miniconda

  All requested packages already installed


Transaction starting

Transaction finished

To activate this environment, use:

    mamba activate base

Or to execute a single command in this environment, use:

    mamba run -n base mycommand



critical libmamba Cannot activate, prefix does not exist at: '/home/cc/miniconda/envs/sixthsense'


--2025-02-22 05:00:14--  https://zenodo.org/record/6388301/files/csvs.tar.gz?download=1
Resolving zenodo.org (zenodo.org)... 188.185.48.194, 188.185.43.25, 188.185.45.92, ...
Connecting to zenodo.org (zenodo.org)|188.185.48.194|:443... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: /records/6388301/files/csvs.tar.gz [following]
--2025-02-22 05:00:14--  https://zenodo.org/records/6388301/files/csvs.tar.gz
Reusing existing connection to zenodo.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 60141155 (57M) [application/octet-stream]
Saving to: ‘sixthsense/csvs/csvs.tar.gz’

     0K .......... .......... .......... .......... ..........  0% 71.9K 13m36s
    50K .......... .......... .......... .......... ..........  0%  379K 8m5s
   100K .......... .......... .......... .......... ..........  0%  146M 5m23s
   150K .......... .......... .......... .......... ..........  0%  197M 4m2s
   200K .......... .......... .......... .......... ...

csvs/timeseries_warmup_runtime_700.csv
csvs/mixture_runtime_70.csv
csvs/mixture_warmup_runtime_700.csv
csvs/timeseries_warmup_runtime_400.csv
csvs/lrm_warmup_runtime_700.csv


2025-02-22 05:00:18 (14.7 MB/s) - ‘sixthsense/csvs/csvs.tar.gz’ saved [60141155/60141155]



csvs/lrm_runtime_60.csv
csvs/mixture_runtime_90.csv
csvs/timeseries_runtime_80.csv
csvs/timeseries_runtime_10.csv
csvs/mixture_runtime_80.csv
csvs/lrm_warmup_runtime_600.csv
csvs/lrm_warmup_runtime_100.csv
csvs/mixture_warmup_runtime_300.csv
csvs/timeseries_warmup_runtime_1000.csv
csvs/mixture_runtime_60.csv
csvs/mixture_runtime_20.csv
csvs/lrm_warmup_runtime_900.csv
csvs/timeseries_runtime_70.csv
csvs/timeseries_runtime_20.csv
csvs/lrm_runtime_70.csv
csvs/timeseries_runtime_90.csv
csvs/timeseries_runtime_50.csv
csvs/lrm_runtime_50.csv
csvs/timeseries_metrics.csv
csvs/timeseries_runtime_100.csv
csvs/mixture_warmup_runtime_600.csv
csvs/timeseries_features.csv
csvs/lrm_warmup_runtime_300.csv
csvs/mixture_warmup_runtime_900.csv
csvs/timeseries_runtime_60.csv
csvs/lrm_features.csv
csvs/mixture_runtime_50.csv
csvs/lrm_runtime_80.csv
csvs/lrm_warmup_runtime_200.csv
csvs/lrm_runtime_20.csv
csvs/mixture_features.csv
csvs/mixture_runtime_40.csv
csvs/timeseries_warmup_runtime_200.csv
csvs/lrm_ru

/home/cc/miniconda/lib/python3.12/site-packages/pandas/core/dtypes/astype.py:133: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)
/home/cc/sixthsense/utils.py:67: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data[metric][0])


Namespace(feature_file=['sixthsense/csvs/lrm_features.csv'], feature_other=None, labels_file=['sixthsense/csvs/lrm_metrics.csv'], metric='rhat_min', threshold=None, ignore_vi=True, split_ratio=0.8, split_template_name='lightspeed', split_by_template=True, balance=False, balance_by_weight=True, algorithm='rf', cv=True, cv_template=False, plot=True, validation=False, learning=False, grid=False, metrics_suffix='avg', runtime=False, predict=None, tree=False, train_by_size=False, split_class=None, shuffle=False, saveas='sixthsense/plots/results_rhat_min_lrm.png', feature_select=False, plt_template=False, warmup=False, stratify_data=False, special_index=None, ignore=None, keep=['_ast_', 'dt_', 'var_min', 'var_max', 'data_size'], selected=None, with_noise=False, tfpn=None, allpreds=False, test_features=None, test_labels=None, runtime_iteration=None, train_size=1.0, metric_filter=None, projection_size=None, max_motifs=0, nooverlap=None)
2.6306503
Infinite: 57
Nans: 0
Threshold : 1.05==========

findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
findfont: Font family 'normal' not found.
Traceback (most recent call last):
  File "/home/cc/sixthsense/train.py", line 719, in <module>
    plot_results(label, results, threshold, xlabels, args.saveas, args)


{'sesame_one_pred_a': 107, 'radon.1': 112, 'mesquite_vas': 135, 'hiv_inter_chr': 128, 'kidscore_momhs': 121, 'electric_1b_chr': 138, 'radon_vary_intercept_nofloor': 115, 'radon_vary_intercept_floor': 119, 'kidiq_interaction': 106, 'mesquite_vash': 128, 'radon_vary_intercept_b': 24, 'radon_vary_intercept_floor2': 76, 'electric_1c': 123, 'hiv_inter': 128, 'radon_vary_intercept_floor_chr': 119, 'wells_dae': 30, 'mesquite_volume': 127, 'radon_intercept_chr': 134, 'election88_expansion': 58, 'radon_inter_vary': 123, 'mesquite_va': 136, 'radon_vary_inter_slope_17.1': 125, 'electric_supp': 121, 'radon_vary_si': 124, 'pilots': 127, 'wells_dist100': 70, 'mesquite_log': 122, 'radon_chr': 130, 'unemployment': 125, 'radon.nopooling': 101, 'ideo_reparam': 120, 'sesame_multi_preds_3a': 115, 'mesquite': 139, 'wells_interaction': 30, 'pilots_chr': 126, 'sesame_one_pred_b': 120, 'flight_simulator_17.3': 128, 'radon_vary_inter_slope_17.2': 71, 'kidiq_interaction_z': 133, 'earnings_vary_si': 138, 'earnin

  File "/home/cc/sixthsense/utils.py", line 156, in plot_results
    write_csv(exp_results, metric_thresholds, metric_label, args)
  File "/home/cc/sixthsense/utils.py", line 47, in write_csv


tric_tr': 129, 'wells_probit': 43, 'weight': 73, 'earnings_latin_square_chr': 102, 'kidiq_interaction_c2': 138, 'electric_1b': 137, 'wells': 60, 'radon_redundant': 82, 'radon': 102, 'dogs_log': 28, 'wells_daae_c': 87, 'electric_inter': 127, 'nes': 42, 'radon_group_chr': 108, 'dogs': 64, 'separation': 108, 'wells_dae_inter_c': 62, 'radon_group': 121, 'radon_intercept': 131, 'kidiq_interaction_c': 119, 'logearn_interaction': 64, 'wells_d100ars': 46, 'earnings_vary_si_chr': 112, 'ideo_interactions': 133, 'election88': 26, 'wells_dist': 61, 'radon_redundant_chr': 59, 'wells_interaction_c': 50, 'wells_dae_c': 76, 'schools': 132, 'logearn_interaction_z': 116, 'electric': 71, 'kidscore_momwork': 14, 'earn_height': 7, 'wells_predicted': 11, 'wells_predicted_log': 6, 'weight_censored': 1}
Test
{'lightspeed': 107}
6360.0
X train size::: 11706
rf-n_est=40
Validation accuracy: 0.8675890842009535
[0.86976943 0.86715079 0.87142247 0.86501495 0.86458778]
X train size::: 11706
rf-n_est=80
Validation a

    with open('results/'+args.saveas.split('/')[1]+'.txt', 'w') as res:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/plots.txt'


ccuracy: 0.867674736649727
[0.86720751 0.86373345 0.8709953  0.87270397 0.86373345]
X train size::: 11706
rf-n_est=100
Validation accuracy: 0.8686142871056951
[0.86976943 0.86501495 0.87142247 0.87056813 0.86629645]
X train size::: 11706
rf-n_est=250
Validation accuracy: 0.8708354141503827
[0.87147737 0.86843229 0.87782999 0.87313114 0.86330628]
X train size::: 11706
rf-n_est=500
Validation accuracy: 0.8698101747667447
[0.87190436 0.86117044 0.87868432 0.8722768  0.86501495]
Best k:  250
[('43_50_98_9_0', 0.025714089402618944), ('31_91_39_76_40', 0.022474210378071114), ('24_91_39_76_40', 0.022064849035002502), ('65_31_39_76_40', 0.021865510601973847), ('65_31_91_39_76', 0.02146562089160326), ('31_39_76_40_50', 0.020509628705868907), ('65_31_43_50_98', 0.019379021116119624), ('91_39_76_40_50', 0.01760235398329548), ('data_size', 0.01709379420782841), ('50_98_9_0_0', 0.016802754423630738), ('31_43_50_98_9', 0.016713708859024984), ('24_50_98_9_0', 0.015986506782578278), ('39_76_40_50_98',

<Result cmd='bash sixthsense/reproduce.sh' exited=0>